RoomBook/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('room_booking/', include('room_booking.urls')),
]

room_booking/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views

app_name = 'room_booking'

urlpatterns = [
	path('',user_views.index,name="index"),
	path('register/',user_views.register,name="register"),
	path('login/',auth_views.LoginView.as_view(template_name = "room_booking/login.html"),name = "login"),
	path('logout/',auth_views.LogoutView.as_view(template_name = "room_booking/logout.html"),name = "logout"),
	path('user_home/',user_views.user_home,name="user-home"),
	path('bookings/',user_views.bookings,name="bookings"),
]

room_booking/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Visitor(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	phone_no = models.CharField(max_length = 10)
	address = models.TextField(max_length=200)

	def __str__(self):
		return self.user.first_name


class Room(models.Model):
	visitor = models.ManyToManyField(Visitor,through= 'Booking')
	room_no =  models.CharField(max_length=4)
	location = models.CharField(max_length=4)
	facilities = models.CharField(max_length=50)

	def __str__(self):
		return self.room_no +' --> '+self.location


class Booking(models.Model):

	visitor = models.ForeignKey(Visitor,models.SET_NULL, blank=True, null=True)
	room = models.ForeignKey(Room,on_delete=models.CASCADE)
	from_date = models.DateField(auto_now=False,auto_now_add =False)
	to_date = models.DateField(auto_now=False,auto_now_add =False)

room_booking/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Visitor,Room,Booking

class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ['first_name','last_name','email','username','password']

class VisitorForm(forms.ModelForm):
	class Meta:
		model = Visitor
		fields = ['phone_no','address']

class RoomsForm(forms.Form):

	from_date = forms.DateField(widget = forms.SelectDateWidget())
	to_date = forms.DateField(widget = forms.SelectDateWidget())

		

room_booking/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Visitor,Room,Booking
from .forms import UserRegistrationForm,VisitorForm,RoomsForm
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.db.models import Q

# Create your views here.




def index(request):
	return render(request,'room_booking/index.html')



def register(request): 

	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST)
		visitor_form = VisitorForm(request.POST)
		if user_form.is_valid() and visitor_form.is_valid():
			user_obj = user_form.save(commit = False)
			user_obj.set_password(user_obj.password)
			user_obj.save()
			visitor_obj = visitor_form.save(commit = False)
			visitor_obj.user = user_obj
			visitor_obj.save()
			return HttpResponseRedirect(reverse('room_booking:login'))
		else:
			context = {'user_form' : user_form, 'visitor_form': visitor_form}
	else:
		user_form = UserRegistrationForm()
		visitor_form = VisitorForm()
		context = {'user_form' : user_form, 'visitor_form': visitor_form}
	return render(request,'room_booking/register.html',context)


def user_home(request):
	if request.method == 'POST':
		flag = 0
		for x in request.POST.keys():
			if x=='room_name':
				flag=1

		if flag ==1:

			form = RoomsForm(request.POST)
			if form.is_valid():
				fd = form.cleaned_data['from_date']
				td = form.cleaned_data['to_date']
				user_obj= User.objects.get(username=request.user)
				b = Booking(from_date=fd,to_date=td,room=Room.objects.get(id=request.POST['room_name']),visitor=Visitor.objects.get(user=user_obj))
				b.save()
				vis = User.objects.get(username = request.user).visitor
				context = {'room':Room.objects.get(id=request.POST['room_name']),
				'user_info':request.user,
				'booking_obj_list':Booking.objects.filter(visitor=vis)}
				return render(request,'room_booking/bookings.html',context)
			# else:
			# 	return HttpResponseRedirect(reverse('room_booking:bookings'))



		else:

			form = RoomsForm(request.POST)
			if form.is_valid():
				fd = form.cleaned_data['from_date']
				td = form.cleaned_data['to_date']
				queries = Booking.objects.exclude((Q(from_date__lt=fd)&Q(to_date__lt=td))|(Q(from_date__gt=fd)&Q(to_date__gt=td)))
				room_list = []
				for q in queries:
					room_list.append(q.room.room_no)
				room_obj_list = Room.objects.exclude(room_no__in=room_list)
				context = {'rooms' : Room.objects.exclude(room_no__in=room_list),'form':form,'fd':fd,'td':td}
	else:
		form = RoomsForm()
		context = {'form' : form}
	return render(request,'room_booking/user_home.html', context)


def bookings(request):

	vis = User.objects.get(username = request.user).visitor
	context= {'booking_obj_list':Booking.objects.filter(visitor=vis)}
	return render(request,'room_booking/bookings.html',context)

room_booking/templates/room_booking/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="#">Room Booking App</a>
	  
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Link</a>
	      </li>
	    </ul>
	  </div>
	  <div class="navbar-nav">
          <strong><a class="nav-item nav-link" href="#">Login</a></strong>
          <strong><a class="nav-item nav-link" href="{% url "room_booking:register" %}">Register</a></strong>
        </div>
	</nav>


	
		{% block content %}{% endblock %}






	
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

room_booking/templates/room_booking/bookings.html
{% extends 'room_booking/base.html' %}

{% block title %}
	Room Booking App 
{% endblock %}


{% block content %}

	{% if room %}
		<div class="container">
			<h1>A New Room has been booked..</h1>
			<h1>Room Details </h1>
			<ul>
				<li>{{ room.room_no }}</li>
				<li>{{ room.location }}</li>
				<li>{{ room.facilities }}</li>
			</ul>
			<h1>User Details</h1>
				<p>{{ user.username }}</p>

		</div>
	{% endif %}

	<div class="container">
		<p></p>
		<h1>Booking History</h1>
		<p></p>
		<p></p>
		<table class="table table-bordered">
				<thead>
					<tr>
						<th scope="col">Booking Id</th>
						<th scope="col">From Date</th>
						<th scope="col">To Date</th>
						<th scope="col">Room Details</th>
					</tr>
				</thead>
				
				<tbody>
					{% for book in booking_obj_list %}
						<tr>
							<th scope="row">{{ book.id }}</td>
							<td>{{ book.from_date }}</td>
							<td>{{ book.to_date }}</td>
							<td>{{ book.room.room_no }}-->{{ book.room.location }}</td>
						</tr>
					{% endfor %}
				</tbody>

			</table>
	</div>

{% endblock %}

room_booking/templates/room_booking/index.html
{% extends 'room_booking/base.html' %}

{% block title %}
	Room Booking App (Changed) 
{% endblock %}


{% block content %}

	<div class="jumbotron">
	  <h1 class="display-4">Room Booking App</h1>
	  
	</div>

{% endblock %}

room_booking/templates/room_booking/login.html
{% extends 'room_booking/base.html' %}

{% block title %}
	LogIn page
{% endblock %}


{% block content %}
	<div class="container">
		<p></p>
		<h1>LogIn Here</h1>
		<p></p>
		<form action="{% url "room_booking:login" %}" method="POST" >
			{% csrf_token %}
			{{ form.as_p }}
			<p></p>
			<input type="submit" name="submit" value="LogIn">	
		</form>
	</div>
	

{% endblock %}

room_booking/templates/room_booking/logout.html
{% extends 'room_booking/base.html' %}

{% block title %}
	Logout page
{% endblock %}


{% block content %}
	<div class="container">
		<p></p>
		<h1>You have been logged out</h1>
		<p></p>
	</div>
	

{% endblock %}

room_booking/templates/room_booking/register.html
{% extends 'room_booking/base.html' %}

{% block title %}
	Register
{% endblock %}


{% block content %}
	<div class="container">
		<p></p>
		<h1>Register Here</h1>
		<p></p>
		<form action="{% url "room_booking:register" %}" method="POST">
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ visitor_form.as_p }}
			<p></p>
			<input class="btn btn-primary"type="submit" name="submit" value="Register">	
		</form>
	</div>

{% endblock %}

room_booking/templates/room_booking/user_home.html
{% extends 'room_booking/base.html' %}

{% block title %}
	LogIn page
{% endblock %}


{% block content %}
	<div class="container">
		<p></p>
		<h1>List of Rooms Available</h1>
		<p></p>
		
		<form action="{% url "room_booking:user-home" %}" method="POST" >
			{% csrf_token %}

			
			{% if form %}
				{{form.as_p}}
			{% endif %}
			
			{% if rooms %}
				<table class="table table-bordered">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Room No</th>
							<th scope="col">Location</th>
							<th scope="col">Facilities</th>
						</tr>
					</thead>
					
					<tbody>
						{% for room in rooms%}
							<tr>
								<th scope="row"><input type="radio" name="room_name" value="{{room.id}}"></th>
								<td>{{ room.room_no }}</td>
								<td>{{ room.location }}</td>
								<td>{{ room.facilities }}</td>
							</tr>
						{% endfor %}
					</tbody>

				</table>
			{% endif %}

			{% if form and rooms %}
				<input type="submit" value="Book Room">
			{% else %}
				<input type="submit" name="submit" value="Show Availability">
			{% endif %}

		</form>
	
		<p></p>

		<form action="{% url "room_booking:bookings" %}" method="POST">
			{% csrf_token %}
			
			<p></p>
			
		</form>

	</div>
	

{% endblock %}